### ISSUE TITLE
Organize include directory into one

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/paradoxOS#9]
I wonder why are you using multiple include directory instead of one. If you are using one include directory, the subdirectory inside will make more sense

**Comment by ParadoxZero** [comment]
Everything inside `include/generic`. I am currently in process of refactoring the project.

**Comment by ParadoxZero** [comment]
if you are referring to `kernel/arch/include`, then that's because it contains headers that should be available to the kernel, yet not part of the system includes.

Why is it in a special directory instead of within `arch/`? Because for every architecture dependent code I write, e.g. ARM, I will have to implement those interfaces.
